# Generated by `rjournal_article()` using `knitr::purl()`: do not edit by hand
# Please edit article.Rmd to modify this file

## ----setup, include=FALSE----------------------------------------------------------------------------------------------------------------------
options(prompt = 'R> ', continue = '+ ')
knitr::opts_chunk$set(purl = TRUE, warning = FALSE, message = FALSE, echo = TRUE, cache = TRUE, include = TRUE, eval = TRUE, fig.align = "center", fig.pos = "!ht")


## ---- echo = FALSE-----------------------------------------------------------------------------------------------------------------------------
show_params("ecxlin")[[1]]


## ---- echo = FALSE-----------------------------------------------------------------------------------------------------------------------------
show_params("ecxexp")[[1]]


## ---- echo = FALSE-----------------------------------------------------------------------------------------------------------------------------
show_params("ecxsigm")[[1]]


## ---- echo = FALSE-----------------------------------------------------------------------------------------------------------------------------
show_params("ecx4param")[[1]]


## ---- echo = FALSE-----------------------------------------------------------------------------------------------------------------------------
show_params("ecxwb1")[[1]]


## ---- echo = FALSE-----------------------------------------------------------------------------------------------------------------------------
show_params("ecxwb1p3")[[1]]


## ---- echo = FALSE-----------------------------------------------------------------------------------------------------------------------------
show_params("ecxwb2")[[1]]


## ---- echo = FALSE-----------------------------------------------------------------------------------------------------------------------------
show_params("ecxwb2p3")[[1]]


## ---- echo = FALSE-----------------------------------------------------------------------------------------------------------------------------
show_params("ecxll5")[[1]]


## ---- echo = FALSE-----------------------------------------------------------------------------------------------------------------------------
show_params("ecxll4")[[1]]


## ---- echo = FALSE-----------------------------------------------------------------------------------------------------------------------------
show_params("ecxll3")[[1]]


## ---- echo = FALSE-----------------------------------------------------------------------------------------------------------------------------
show_params("ecxhormebc5")[[1]]


## ---- echo = FALSE-----------------------------------------------------------------------------------------------------------------------------
show_params("ecxhormebc4")[[1]]


## ---- echo = FALSE-----------------------------------------------------------------------------------------------------------------------------
show_params("neclin")[[1]]


## ---- echo = FALSE-----------------------------------------------------------------------------------------------------------------------------
show_params("nec3param")[[1]]


## ---- echo = FALSE-----------------------------------------------------------------------------------------------------------------------------
show_params("nec4param")[[1]]


## ---- echo = FALSE-----------------------------------------------------------------------------------------------------------------------------
show_params("nechorme")[[1]]


## ---- echo = FALSE-----------------------------------------------------------------------------------------------------------------------------
show_params("nechormepwr")[[1]]


## ---- echo = FALSE-----------------------------------------------------------------------------------------------------------------------------
show_params("neclinhorme")[[1]]


## ---- echo = FALSE-----------------------------------------------------------------------------------------------------------------------------
show_params("nechorme4")[[1]]


## ---- echo = FALSE-----------------------------------------------------------------------------------------------------------------------------
show_params("nechorme4pwr")[[1]]


## ---- echo = FALSE-----------------------------------------------------------------------------------------------------------------------------
show_params("nechormepwr01")[[1]]


## ---- echo = FALSE-----------------------------------------------------------------------------------------------------------------------------
show_params("necsigm")[[1]]


## ---- eval = FALSE-----------------------------------------------------------------------------------------------------------------------------
#> response ~ crf(predictor, model = "a_model")


## ---- eval = FALSE-----------------------------------------------------------------------------------------------------------------------------
#> response | trials(n_trials) ~ crf(log(predictor), model = "a_model")


## ----------------------------------------------------------------------------------------------------------------------------------------------
library(bayesnec)
df <- data.frame(x = rgamma(100, 2, 0.1), y = rnorm(100))
form <- bnf(y ~ crf(log(x), model = "nec3param"))
head(model.frame(form, df))


## ---- warning = FALSE, message = FALSE, results = "hide", cache = TRUE-------------------------------------------------------------------------
data(herbicide)
# filter for one herbicide only
data <- herbicide[herbicide$herbicide == "diuron", ]
set.seed(333)
fit <- bnec(fvfm ~ crf(log(concentration), model = "nec4param"), data = data)


## ---- warning = FALSE, message = FALSE---------------------------------------------------------------------------------------------------------
summary(fit)


## ----base-plot, fig.height = 3.5, fig.width = 4, fig.cap = "\\pkg{ggplot2} `autoplot` of the example fit. The solid black line is the fitted median of the posterior prediction, dashed black lines are the 95\\% credible intervals, and the red vertical lines show the estimated \\textit{NEC} value."----
round_digits <- function(x) sprintf("%.2f", x)
autoplot(fit, xform = exp) +
  scale_x_continuous(trans = "log", labels = round_digits)
# or alternatively
# plot(fit, xform = exp, log = "x")


## ----brmsplot, fig.width = 5.14, fig.height = 6, fig.cap = "Default \\pkg{brms} plot of the \\texttt{nec4param} model showing the posterior densities and chain mixing for each of the included parameters.", dependson="fit"----
plot(fit$fit)


## ----sampleprior, fig.height = 4, fig.width = 4.5, fig.cap = "Frequency histograms of samples of the default priors used by bnec for fitting the \\texttt{nec4param} model to the example data."----
sample_priors(fit$fit$prior)


## ----checkpriorsingle, fig.height = 4, fig.width = 6, fig.cap = "A comparison of the prior and posterior parameter probability densities for the \\texttt{nec4param} model fit to the example data."----
check_priors(fit)


## ----drccomparison, echo = FALSE, fig.width = 6, fig.height = 8, fig.cap = "TBW."--------------------------------------------------------------
library(drc)
library(MASS)
library(corpcor)
library(tidyverse)
library(ggdist)
options(mc.cores = parallel::detectCores())

rounded <- function(value, precision = 1) {
  sprintf(paste0("%.", precision, "f"), round(value, precision))
}

nec3param <- function(beta, nec, top, x) {
  top * exp(-beta * (x - nec) * ifelse(x - nec < 0, 0, 1))
}

my_rmvnorm <- function(mu, Sigma) {
  r <- length(mu)
  L <- try(t(chol(Sigma)))
  if (inherits(L, "try-error")) {
    L <- t(chol(Sigma, pivot = TRUE))
  }
  Z <- rnorm(r)
  (L %*% Z + mu)[, 1]
}

ggdrc_data <- function(x) {
  nec_mean_drc <- summary(x)$coefficients["e:(Intercept)", "Estimate"]
  nec_cis_drc <- confint(x)["e:(Intercept)", ]
  drc_nec <- c(`50%` = nec_mean_drc, `2.5%` = nec_cis_drc[["2.5 %"]],
               `97.5%` = nec_cis_drc[["97.5 %"]])
  mod_df <- x$data
  df_x <- data.frame(log_x = seq(min(mod_df$log_x), max(mod_df$log_x),
                     length = 100))
  mu <- coef(x)
  Sigma <- drc:::vcov.drc(x)
  is_pos_def <- corpcor::is.positive.definite(Sigma)
  if (!is_pos_def) {
    Sigma <- corpcor::make.positive.definite(Sigma, tol = 1e-3)
  }
  Y <- matrix(0, 1000, nrow(df_x))
  pars_mv <- MASS::mvrnorm(n = nrow(Y), mu, Sigma)
  for (i in seq_len(nrow(Y))) {
    Y[i, ] <- nec3param(beta = pars_mv[i, 1], nec = pars_mv[i, 3],
                        top = pars_mv[i, 2], df_x$log_x)
  }
  preds <- apply(Y, 2, median_hdci, na.rm = TRUE) %>%
    do.call("rbind.data.frame", args = .) %>%
    dplyr::select(y, ymin, ymax)
  e_df <- data.frame(x_e = c(df_x$log_x, rev(df_x$log_x)),
                     y_e = c(preds$y, rep(NA, nrow(preds))),
                     y_ci = c(preds$ymin, rev(preds$ymax)),
                     x_r = NA, y_r = NA, nec_vals = NA, nec_labs = NA,
                     nec_labs_l = NA, nec_labs_u = NA)
  r_df <- data.frame(x_e = NA, y_e = NA, y_ci = NA,
                     x_r = mod_df$log_x, y_r = mod_df$fvfm, nec_vals = NA,
                     nec_labs = NA, nec_labs_l = NA, nec_labs_u = NA)
  n_df <- data.frame(x_e = NA, y_e = NA, y_ci = NA,
                     x_r = NA, y_r = NA, nec_vals = drc_nec,
                     nec_labs = c(rounded(drc_nec[[1]], 2), NA, NA),
                     nec_labs_l = c(rounded(drc_nec[[2]], 2), NA, NA),
                     nec_labs_u = c(rounded(drc_nec[[3]], 2), NA, NA))
  rbind(e_df, r_df, n_df)
}

combine_fits <- function(x) {
  # irgarol doesnt fit well in drc, conf int unreliable
  ltys <- rep(rep(c(1, 2, 2), length(unique(x$model))), 2)[-c(36:35)]
  lwds <- rep(rep(c(0.5, 0.2, 0.2), length(unique(x$model))), 2)[-c(36:35)]
  ggplot() +
    geom_polygon(data = x %>% filter(!is.na(y_ci)),
                 mapping = aes(x = x_e, y = y_ci, fill = source),
                 alpha = 0.5, show.legend = FALSE) +
    geom_line(data = x %>% filter(!is.na(y_e)),
              mapping = aes(x = x_e, y = y_e, colour = source),
              linetype = 2, show.legend = FALSE) +
    geom_point(data = x %>% filter(!is.na(y_r)),
               mapping = aes(x = x_r, y = y_r), fill = "grey30",
               shape = 21, show.legend = FALSE) +
    geom_vline(data = x %>% filter(!is.na(nec_vals)),
               mapping = aes(xintercept = nec_vals, colour = source),
               linetype = ltys, lwd = lwds, show.legend = FALSE) +
    geom_text(data = x %>% filter(!is.na(nec_labs), source == "bayesnec"),
              mapping = aes(label = paste0("bayesnec: ", nec_labs, " (",
                                           nec_labs_l, " : ",
                                           nec_labs_u, ")")),
              x = Inf, y = Inf, hjust = 1.1, vjust = 1.5, size = 3,
              colour = "tomato") +
    geom_text(data = x %>% filter(!is.na(nec_labs), source == "drc"),
              mapping = aes(label = paste0("drc: ", nec_labs, " (",
                                           nec_labs_l, " : ",
                                           nec_labs_u, ")")),
              x = Inf, y = Inf, hjust = 1.1, vjust = 4, size = 3,
              colour = "skyblue2") +
    scale_colour_manual(values = c(bayesnec = "tomato", drc = "skyblue2")) +
    scale_fill_manual(values = c(bayesnec = "tomato", drc = "skyblue2")) +
    ylim(0, 0.8) +
    theme_classic() +
    facet_wrap(~model, scales = "free", ncol = 2) +
    theme(strip.text = element_text(hjust = 0),
          panel.grid.major = element_blank(),
          panel.grid.minor = element_blank(),
          strip.background = element_blank(),
          panel.border = element_rect(colour = NA, fill = NA)) +
    labs(x = "Concentration (natural log)",
         y = "PAM")
}

df_list <- herbicide %>%
  dplyr::mutate(log_x = log(concentration)) %>%
  dplyr::arrange(herbicide, concentration) %>%
  split(f = ~ herbicide)

bnec_list <- purrr::map(
  df_list, ~bnec(formula = fvfm ~ crf(log_x, model = "nec3param"), data = .x)
)
drc_list <- purrr::map(
  df_list, ~drm(formula = fvfm ~ log_x, fct = NEC.3(),
                data = .x)
)

if (!all(names(bnec_list) == names(drc_list))) {
  stop("Incompatible name order.")
}

bnec_plot_data <- purrr::map_dfr(bnec_list, ggbnec_data, .id = "model") %>%
  dplyr::mutate(source = "bayesnec")
drc_plot_data <- purrr::map_dfr(drc_list, ggdrc_data, .id = "model") %>%
  dplyr::mutate(source = "drc")
plot_data <- rbind(bnec_plot_data, drc_plot_data)

combine_fits(plot_data)


## ----sessioninfo, eval=TRUE, include=FALSE-----------------------------------------------------------------------------------------------------
sessionInfo()

