// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppEigen.h>
#include <Rcpp.h>

using namespace Rcpp;


RcppExport SEXP _rcpp_module_boot_stan_fit4ecxexpbeta_mod();
RcppExport SEXP _rcpp_module_boot_stan_fit4ecxexpbinom_mod();
RcppExport SEXP _rcpp_module_boot_stan_fit4ecxexpgamma_mod();
RcppExport SEXP _rcpp_module_boot_stan_fit4ecxexpgaussian_mod();
RcppExport SEXP _rcpp_module_boot_stan_fit4ecxexpnegbin_mod();
RcppExport SEXP _rcpp_module_boot_stan_fit4ecxexppoisson_mod();

static const R_CallMethodDef CallEntries[] = {
    {"_rcpp_module_boot_stan_fit4ecxexpbeta_mod", (DL_FUNC) &_rcpp_module_boot_stan_fit4ecxexpbeta_mod, 0},
    {"_rcpp_module_boot_stan_fit4ecxexpbinom_mod", (DL_FUNC) &_rcpp_module_boot_stan_fit4ecxexpbinom_mod, 0},
    {"_rcpp_module_boot_stan_fit4ecxexpgamma_mod", (DL_FUNC) &_rcpp_module_boot_stan_fit4ecxexpgamma_mod, 0},
    {"_rcpp_module_boot_stan_fit4ecxexpgaussian_mod", (DL_FUNC) &_rcpp_module_boot_stan_fit4ecxexpgaussian_mod, 0},
    {"_rcpp_module_boot_stan_fit4ecxexpnegbin_mod", (DL_FUNC) &_rcpp_module_boot_stan_fit4ecxexpnegbin_mod, 0},
    {"_rcpp_module_boot_stan_fit4ecxexppoisson_mod", (DL_FUNC) &_rcpp_module_boot_stan_fit4ecxexppoisson_mod, 0},
    {NULL, NULL, 0}
};

RcppExport void R_init_bayesnec(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
