# Generated by rstantools.  Do not edit by hand.

# names of stan models
stanmodels <- c("ecx4parambeta", "ecx4parambinom", "ecx4paramgamma", "ecx4paramgaussian", "ecx4paramnegbin", "ecx4parampoisson", "ecxexpbeta", "ecxexpbinom", "ecxexpgamma", "ecxexpgaussian", "ecxexpnegbin", "ecxexppoisson", "ecxlinbeta", "ecxlinbinom", "ecxlingamma", "ecxlingaussian", "ecxlinnegbin", "ecxlinpoisson", "ecxsigmbeta", "ecxsigmbinom", "ecxsigmgamma", "ecxsigmgaussian", "ecxsigmnegbin", "ecxsigmpoisson", "ecxwb1beta", "ecxwb1binom", "ecxwb1gamma", "ecxwb1gaussian", "ecxwb1negbin", "ecxwb1poisson", "ecxwb2beta", "ecxwb2binom", "ecxwb2gamma", "ecxwb2gaussian", "ecxwb2negbin", "ecxwb2poisson", "nec3parambeta", "nec3parambinom", "nec3paramgamma", "nec3paramgaussian", "nec3paramnegbin", "nec3parampoisson", "nec4parambeta", "nec4parambinom", "nec4paramgamma", "nec4paramgaussian", "nec4paramnegbin", "nec4parampoisson", "nechormebeta", "nechormebinom", "nechormegamma", "nechormegaussian", "nechormenegbin", "nechormepoisson", "necsigmbeta", "necsigmbinom", "necsigmgamma", "necsigmgaussian", "necsigmnegbin", "necsigmpoisson")

# load each stan module
Rcpp::loadModule("stan_fit4ecx4parambeta_mod", what = TRUE)
Rcpp::loadModule("stan_fit4ecx4parambinom_mod", what = TRUE)
Rcpp::loadModule("stan_fit4ecx4paramgamma_mod", what = TRUE)
Rcpp::loadModule("stan_fit4ecx4paramgaussian_mod", what = TRUE)
Rcpp::loadModule("stan_fit4ecx4paramnegbin_mod", what = TRUE)
Rcpp::loadModule("stan_fit4ecx4parampoisson_mod", what = TRUE)
Rcpp::loadModule("stan_fit4ecxexpbeta_mod", what = TRUE)
Rcpp::loadModule("stan_fit4ecxexpbinom_mod", what = TRUE)
Rcpp::loadModule("stan_fit4ecxexpgamma_mod", what = TRUE)
Rcpp::loadModule("stan_fit4ecxexpgaussian_mod", what = TRUE)
Rcpp::loadModule("stan_fit4ecxexpnegbin_mod", what = TRUE)
Rcpp::loadModule("stan_fit4ecxexppoisson_mod", what = TRUE)
Rcpp::loadModule("stan_fit4ecxlinbeta_mod", what = TRUE)
Rcpp::loadModule("stan_fit4ecxlinbinom_mod", what = TRUE)
Rcpp::loadModule("stan_fit4ecxlingamma_mod", what = TRUE)
Rcpp::loadModule("stan_fit4ecxlingaussian_mod", what = TRUE)
Rcpp::loadModule("stan_fit4ecxlinnegbin_mod", what = TRUE)
Rcpp::loadModule("stan_fit4ecxlinpoisson_mod", what = TRUE)
Rcpp::loadModule("stan_fit4ecxsigmbeta_mod", what = TRUE)
Rcpp::loadModule("stan_fit4ecxsigmbinom_mod", what = TRUE)
Rcpp::loadModule("stan_fit4ecxsigmgamma_mod", what = TRUE)
Rcpp::loadModule("stan_fit4ecxsigmgaussian_mod", what = TRUE)
Rcpp::loadModule("stan_fit4ecxsigmnegbin_mod", what = TRUE)
Rcpp::loadModule("stan_fit4ecxsigmpoisson_mod", what = TRUE)
Rcpp::loadModule("stan_fit4ecxwb1beta_mod", what = TRUE)
Rcpp::loadModule("stan_fit4ecxwb1binom_mod", what = TRUE)
Rcpp::loadModule("stan_fit4ecxwb1gamma_mod", what = TRUE)
Rcpp::loadModule("stan_fit4ecxwb1gaussian_mod", what = TRUE)
Rcpp::loadModule("stan_fit4ecxwb1negbin_mod", what = TRUE)
Rcpp::loadModule("stan_fit4ecxwb1poisson_mod", what = TRUE)
Rcpp::loadModule("stan_fit4ecxwb2beta_mod", what = TRUE)
Rcpp::loadModule("stan_fit4ecxwb2binom_mod", what = TRUE)
Rcpp::loadModule("stan_fit4ecxwb2gamma_mod", what = TRUE)
Rcpp::loadModule("stan_fit4ecxwb2gaussian_mod", what = TRUE)
Rcpp::loadModule("stan_fit4ecxwb2negbin_mod", what = TRUE)
Rcpp::loadModule("stan_fit4ecxwb2poisson_mod", what = TRUE)
Rcpp::loadModule("stan_fit4nec3parambeta_mod", what = TRUE)
Rcpp::loadModule("stan_fit4nec3parambinom_mod", what = TRUE)
Rcpp::loadModule("stan_fit4nec3paramgamma_mod", what = TRUE)
Rcpp::loadModule("stan_fit4nec3paramgaussian_mod", what = TRUE)
Rcpp::loadModule("stan_fit4nec3paramnegbin_mod", what = TRUE)
Rcpp::loadModule("stan_fit4nec3parampoisson_mod", what = TRUE)
Rcpp::loadModule("stan_fit4nec4parambeta_mod", what = TRUE)
Rcpp::loadModule("stan_fit4nec4parambinom_mod", what = TRUE)
Rcpp::loadModule("stan_fit4nec4paramgamma_mod", what = TRUE)
Rcpp::loadModule("stan_fit4nec4paramgaussian_mod", what = TRUE)
Rcpp::loadModule("stan_fit4nec4paramnegbin_mod", what = TRUE)
Rcpp::loadModule("stan_fit4nec4parampoisson_mod", what = TRUE)
Rcpp::loadModule("stan_fit4nechormebeta_mod", what = TRUE)
Rcpp::loadModule("stan_fit4nechormebinom_mod", what = TRUE)
Rcpp::loadModule("stan_fit4nechormegamma_mod", what = TRUE)
Rcpp::loadModule("stan_fit4nechormegaussian_mod", what = TRUE)
Rcpp::loadModule("stan_fit4nechormenegbin_mod", what = TRUE)
Rcpp::loadModule("stan_fit4nechormepoisson_mod", what = TRUE)
Rcpp::loadModule("stan_fit4necsigmbeta_mod", what = TRUE)
Rcpp::loadModule("stan_fit4necsigmbinom_mod", what = TRUE)
Rcpp::loadModule("stan_fit4necsigmgamma_mod", what = TRUE)
Rcpp::loadModule("stan_fit4necsigmgaussian_mod", what = TRUE)
Rcpp::loadModule("stan_fit4necsigmnegbin_mod", what = TRUE)
Rcpp::loadModule("stan_fit4necsigmpoisson_mod", what = TRUE)

# instantiate each stanmodel object
stanmodels <- sapply(stanmodels, function(model_name) {
  # create C++ code for stan model
  stan_file <- if(dir.exists("stan")) "stan" else file.path("inst", "stan")
  stan_file <- file.path(stan_file, paste0(model_name, ".stan"))
  stanfit <- rstan::stanc_builder(stan_file,
                                  allow_undefined = TRUE,
                                  obfuscate_model_name = FALSE)
  stanfit$model_cpp <- list(model_cppname = stanfit$model_name,
                            model_cppcode = stanfit$cppcode)
  # create stanmodel object
  methods::new(Class = "stanmodel",
               model_name = stanfit$model_name,
               model_code = stanfit$model_code,
               model_cpp = stanfit$model_cpp,
               mk_cppmodule = function(x) get(paste0("model_", model_name)))
})
