---
title: 'bayesnec: An R package for Concentration-Response modelling and estimation of No-Effect-Concentrations'
tags:
  - R
  - concentration response
  - ecotoxicology
  - effect concentration
  - threshold derivation
  - nec
authors:
  - name: Rebecca Fisher
    orcid: 0000-0001-5148-6731
    affiliation: "1, 2"
  - name: Diego Barneche
    orcid: 0000-0002-4568-2362
    affiliation: "1, 2"
affiliations:
 - name: Australian Institute of Marine Science, Australia
   index: 1
 - names: The Indian Ocean Marine Research Centre, University of Western Australia, Australia
   index: 2

citation_author: Fisher & Barneche
date: 20 January 2021
bibliography: paper.bib
output: rticles::joss_article
csl: apa.csl
journal: JOSS
---

# Summary

The `bayesnec` is an R package to fit concentration(dose) - response curves to toxicity data, and derive No-Effect-Concentration (*NEC*), No-Significant-Effect-Concentration (*NSEC*), and Effect-Concentration (of specified percentage 'x', *ECx*) thresholds from non-linear models fitted using Bayesian MCMC fitting methods via `brms` [@Burkner2017; @Burkner2018] and `stan`. The package is an adaptation and extension of an initial package `jagsNEC` [@Fisher2020] which was based on the `R2jags` package [@Su2015] and `jags` [@Plummer2003]. In `bayesnec` it is possible to fit a single model, custom model set, specific model set or all of the available models. When multiple models are specified the `bnec` function returns a model weighted estimate of predicted posterior values. A range of support functions and methods are also included to work with the returned single, or multi- model objects that allow extraction of raw or model averaged predicted, ECx, NEC and NSEC values and to interrogate the fitted model or model set.


# Statement of need

Concentration-response (C-R) modelling is fundamental to assessing toxicity and deriving toxicity thresholds used in the risk assessments that underpin protection of human health and the environment. They are widespread in the disciplines of pharmacology, toxicology and ecotoxicoloy. Typically C-R curves are non-linear, which increases the complexity of their numerical estimation. Additionally, estimates of uncertainty in parameters and derived thresholds are critical to effective integration in risk assessment and formal decision frameworks. Bayesian methods that allow robust quantification of uncertainty with intuitive and direct probabilistic meaning are therefore ideal tools C-R modelling in most settings.

Bayesian model fitting can be difficult to automate across a broad range of usage cases, particularly with respect to specifying valid initial values and appropriate priors. This is one reason the use of Bayesian statistics for *NEC* estimation (or even *ECx* estimation) is not currently widely adopted across the broader ecotoxicological and toxicology community, who rarely have access to specialist statistical expertise. The `bayesnec` package provides an accessible interface specifically for fitting *NEC* models and other concentration-response models using Bayesian methods. A range of models can be specified based on the known distribution of the "concentration" or "dose" variable (the predictor, x) as well as the "response" (y) variable. The model formula, including priors and initial values required to call a `brms` model are automatically generated based on information contained in the supplied data.

# Development and Functionality

This project started with an implementation of the *NEC* model based on that described in [@Fox2010] using R2jags. The package has been further generalised to allow a large range of response variables to be modelled using the appropriate statistical distribution. While the original `jagsNEC` implementation supported gaussian, poisson, binomial, gamma, negbin and beta response data `bayesnec` supports any of the `brms` families. We have since also further added a range of alternative *NEC* model types, as well as a range of typically used concentration-response models (such as 4-parameter logistic and weibull models) that have no *NEC* 'step' function but simply model the response as a smooth function of concentration, as can be fit using other commonly used frequentist packages such as `drc` [@Ritz2016].

The main working function in `bayesnec` is `bnec` Specific models can be fit directly using `bnec`, in which case an object of class `bayesnecfit` is returned. Alternatively it is possible to fit a custom model set, specific model set or all of the available models. Were multiple models are fit a `bayesmanecfit` model object is returned, and a model averaging approached is used to synthesise the returned output (see below for more details). 

We have attempted to make the `bnec` function as easy to use as possible, targeting the novice R user, whilst ensuring the important relevant arguments can be set and modified as required by those more advanced. Only three arguments must be supplied, including: `data` - A `data.frame` containing the data to use for the model; `x_var` - A `character` indicating the column heading containing the concentration (x) variable; and `y_var` - A `character` indicating the column heading containing the response (y) variable. While the distribution of the x and y variables can be specified directly, `bayesnec` will automatically 'guess' the correct distribution to use based on the characteristics of the provided data, as well as build the relevant model priors and initial values for the `brms` model.

The statistical families available for modelling the response variabe `y_var` include binomial, beta, betabinomial, poisson, gamma, gaussian, and negative binomal. If not supplied, the appropriate distribution will be guessed based on the characteristics of the input data through `check_data`. Guesses include all of the available families except negbinomial and betabinomimal because these requires knowledge on whether the data is over-dispersed. 

## Model diagnostics

`bayesnec` includes a summary method for both `bayesnecfit` and `bayesmanecfit` model objects the provides the usual summary of the model a parameters, along with any relevant model fits statistics as returned in the underlying `brm` model fits.

A range of tools are available to the user to assess model fit, including an estimate of overdispersion (for relevant families), an extension of the `brms` `rhat` function that can be applied both `bayesnecfit` and `bayesmanecfit` model objects and a function `check_chains` that can be used to visually assess chain mixing.

Several helper functions have been included that allow the user to add or drop models from a `bayesmanecfit` object , or change the model weighting method (`amend`); extract a single or subset of models from the `bayesmanecfit` object (`pull_out`); and examine the priors use for model fitting (`pull_prior` and `sample_prior`).

## Model inference

Base R (`plot`) and ggplot2 (`ggbnec`) plotting methods, as well as predict methods have also been developed for both `bayesnecfit` and `bayesmanecfit` model classes. In addition, there are method based functions for extracting ECx (`ecx`), NEC (`nec`) and NSEC (`nsec`) threshold values. In all cases the posterior samples that underpin these functions are achieved through `posterior_epred` from the `brms` package.

# Models in `bayesnec`

There are a range of models available in `bayesnec`. 

The argument `model` in the function `bnec` is a character string indicating the name(s) of the desired model (see ?models for more details, and the list of models available). If a recognised model name is provided a single model of the specified type is fit, and `bnec` returns a model object of class `bayesnecfit`. If a vector of two or more of the available models are supplied, `bnec` returns a model object of class `bayesmanecfit` containing Bayesian model averaged predictions for the supplied models, providing they were successfully fitted.

The `model` argument may also be one of "all", meaning all of the available models will be fit; "ecx" meaning only models excluding the $\eta = \text{NEC}$ step parameter will be fit; or "nec" meaning only models with the $\eta = \text{NEC}$ step parameter (see below **Model parameters**) will be fit. There are a range of other pre-define model groups available. The full list of currently implemented model groups can be seen using:

```{r, eval=FALSE}
library("bayesnec")
models()
```

## Parameter definitions

Where possible we have aimed for consistency in the interpretable meaning of the individual parameters across models. Across the currently implemented model set, models contain from two (basic linear or exponential decay, see **ecxlin** or **ecxexp**) to five possible parameters (**nechorme4**), including: 
$\tau = \text{top}$, usually interpretable as either the y-intercept or the upper plateau representing the mean concentration of the response at zero concentration;
$\eta = \text{NEC}$, the no-effect-concentration value (the x concentration value where the breakpoint in the regression is estimated at, see **Model types for NEC and ECx estimation** and [@Fox2010] for more details on parameter based NEC estimation); 
$\beta = \text{beta}$, generally the exponential decay rate of response, either from 0 concentration or from the estimated $\eta$ value, with the exception of the **neclinhorme** model where it represents a linear decay from $\eta$ because slope ($\epsilon$) is required for the linear increase;
$\delta = \text{bottom}$, representing the lower plateau for the response at infinite concentration; 
$\alpha = \text{slope}$, the linear decay rate in the models **neclin** and **ecxlin**, or the linear increase rate prior to $\eta$ for all hormesis models; and 
$\epsilon = \text{d}$, the exponent in the **ecxsigm** and **necisgm** models.

In addition to the model parameters, all `nec...`  models have a step function used to define the breakpoint in the regression, which can be defined as

$$
f(x_i, \eta) = \begin{cases} 
      x_i - \eta < 0, & 0 \\
      x_i - \eta \geq 0, & 1 \\
   \end{cases}
$$


## Model types for NEC and ECx estimation

All models provide an estimate for the No-Effect-Concentration (NEC). For model types with "nec" as a prefix, the NEC is directly estimated as parameter $\eta = \text{NEC}$ in the model, as per [@Fox2010]. Models with "ecx" as a prefix are continuous curve models, typically used for extracting ECx values
from concentration response data. In this instance the NEC reported is actually the No-Significant-Effect-Concentration (NSEC), defined as the concentration at which there is
a user supplied (see `sig_val`) percentage certainty (based on the Bayesian posterior estimate) that the response
falls below the estimated value of the upper asymptote ($\tau = \text{top}$) of the response (i.e. the response value is significantly
lower than that expected in the case of no exposure). The default value for `sig_val` is 0.01, which corresponds to an alpha value (Type 1 error rate) of 0.01 for a one-sided test of significance. See `?nsec` for more details. We currently recommend only using the "nec" model set for estimation of NEC values, as the NSEC concept has yet to be formally peer-reviewed. 

ECx estimates can be equally validly obtained from both "nec" and "ecx" models. ECx estimates will usually be lower (more conservative) for "ecx" models fitted to the same data as "nec" models (see the [Comparing posterior predictions][e4] vignette for an example. However, we recommend using "all" models where ECx estimation is required because "nec" models can fit some datasets better than "ecx" models and the model averaging approach will place the greatest weight for the outcome that best fits the supplied data. This approach will yield ECx estimates that are the most representative of the underlying relationship in the dataset.

There is ambiguity in the definition of ECx estimates from hormesis models (these allow an initial increase in the response (see [@Mattson2008]) and include models with the character string `horme` in their name), as well as those that have no natural lower bound on the scale of the response (models with the string `lin` in their name, in the case of gaussian response data). For this reason the `ecx` function has arguments `hormesis_def` and `type`, both character vectors indicating the desired behaviour. For `hormesis_def = "max"` ECx values are calculated as a decline from the maximum estimates (i.e. the peak at $\eta = \text{NEC}$); and `hormesis_def = "control"` (the default) indicates ECx values should be calculated relative to the control, which is assumed to be the lowest observed concentration. For `type = "relative"` ECx is calculated as the percentage decrease from the maximum predicted value of the response ($\tau = \text{top}$) to the minimum predicted value of the response (ie, 'relative' to the observed data). For `type = "absolute"` (the default) ECx is calculated as the percentage decrease from the maximum value of the response ($\tau = \text{top}$) to 0 (or $\delta = \text{bottom}$ for models with that parameter). For `type = "direct"` a direct interpolation of y on x is obtained.


## Model suitability for response types

Models that have an exponential decay (most models with parameter $\beta = \text{beta}$) with no $\delta = \text{bottom}$ parameter are `0` bounded and are not suitable for the gaussian family, or any family modelled using a logit or log link because they cannot generate predictions of negative y (response). Conversely models with a linear decay (containing the string "lin" in their name) are not suitable for modelling families that are `0` bounded (gamma, poisson, negative binomial) using an identity link. Models with a linear decay or hormesis linear increase (all models with parameter $\alpha = \text{slope}$) are not suitable for modelling families that are `0`, `1` bounded (binomial, beta and betabinomial2). These restrictions do not need to be controlled by the user as a call to `bnec` with `models = "all"` will simply exclude inappropriate models, albeit with a warning.


# Model averaging and multimodel inference

When multiple models are fit using `bnec` an object of class `bayesmanecfit` is returned that includes a model weighted estimate of predicted posterior values. `bayesnec` also includes a set of `bayesmanecfit` methods for predicting, plotting and extracting effect concentrations and related threshold values that return model weighted estimates. 

Multi-model inference can be useful where there are a range of plausible models that could be used [@Burnham2002] and has been recently adopted in ecotoxicology for SSD model inference [@Thorley2018]. The approach may have considerable value in concentration-response modelling because there is often no a priori knowledge of the functional form that the response relationship should take. In this case model averaging can be a useful way of allowing the data to drive the model selection processing, with weights proportional to how well the individual models fits the data. Well fitting models will have high weights, dominating the model averaged outcome. Conversely, poorly fitting models will have very low model weights and will therefore have little influence on the outcome. Were multiple models fit the data equally well, these  can equally influence the outcome, and the resultant posterior predictions reflect that model uncertainty. It is possible to specify the "stacking" method [@Yao2018] for model weights if desired (through the argument `loo_controls`) which aim to minimise prediction error. We do not currently recommend using stacking weights given the typical sample sizes associated with most concentration-response experiments, and because the main motivation for model averaging within the `bayesnec` package is to properly capture model uncertainty rather than reduce prediction error. By default `model weights`bnec` uses the  "pseudobma" method with Bayesian bootstrap through `loo_model_weights` [@vehtari2020; @vehtari2017]. These are reasonably analogous to the way model weights are generated using AIC or AICc [@Burnham2002].


# Model comparison

With `bayesnec` we have included a function (`compare_posterior`) that allows bootstrapped comparisons of posterior predictions. This function allows the user to fit several different `bnec` model fits and can compare differences in the posterior predictions across these fits for individual endpoint estimates (e.g. nec, nsec or ecx) or across a range of predictor (x) values. Usage is demonstrated in the relevant vignette by comparing different types of models and model sets using a single dataset. However, the intent of this function is to allow comparison across different datasets that might represent, for example, different levels of a fixed factor covariate. At this time `bnec` does not allow inclusion of an interaction with a fixed factor. Including an interaction term within each of the non-linear models implemented in `bayesnec` is relatively straightforward, and may be introduced in future releases. However, in many cases the functional form of the response may change with different levels of a given factor. The substantial complexity of defining all possible non-linear model combinations at each factor level means it unlikely this could be feasibly implemented in `bayesnec` in the short term. In the meantime the greatest flexibility in the functional form of individual model fits can be readily obtained using models fitted independently to data within each factor level.

# Acknowledgements

The development of `bayesnec` was supported by an AIMS internal grant. David Fox and Gerard Ricardo developed some of the initial code on which the `bayesnec` predecessor `jagsNEC` was based. Usage, testing and functionality of both the `jagsNEC` and `bayesnec` packages was substantially aided through input from Joost van Dam, Andrew Negri, Florita Florence, Heidi Luter, Marie Thomas and Mikaela Nordborg.


# References
