on:
  push:
    branches:
      - pkg_build_v1
  pull_request:
    branches:
      - pkg_build_v1

name: pkgdown

jobs:
  pkgdown:
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v2

      - uses: r-lib/actions/setup-r@master

      - uses: r-lib/actions/setup-pandoc@master

      - name: Query dependencies
        run: |
          install.packages('remotes')
          saveRDS(remotes::dev_package_deps(dependencies = TRUE), ".github/depends.Rds", version = 2)
        shell: Rscript {0}

      - name: Install dependencies
        run: |
          install.packages(c("ps", "remotes", "tidyverse", "anytime"))
          remotes::install_deps(dependencies = TRUE)
          remotes::install_dev("pkgdown")
        shell: Rscript {0}

      - name: Install package
        run: |
          install.packages(c("Rcpp", "rstantools", "pkgbuild", "roxygen2", "devtools"))
          pkgbuild::compile_dll()
          roxygen2::roxygenise()
          devtools::build()
          devtools::install(quick = FALSE, build_vignettes = FALSE)
        shell: Rscript {0}

      - name: Deploy package
        run: pkgdown::deploy_to_branch(new_process = FALSE)
        shell: Rscript {0}
